### ISSUE TITLE
Custom research not working as intended?

### ISSUE THREAD

**Issue by Dasky14** [JPANv2/ResearchFrom14#1]
Either I'm missing something, or this doesn't work. I wanted the rare keys to have research requirement of 1.
![image](https://user-images.githubusercontent.com/16979168/83788606-22f8dd80-a69e-11ea-9a77-e3335e08f4cf.png)
![image](https://user-images.githubusercontent.com/16979168/83788648-34da8080-a69e-11ea-9044-4785a78fb662.png)

**Comment by JPANv2** [comment]
This happened because keys and keymolds shared the same ID. Items with similar problems would override the given values when reaching the second item with the same id. It has been fixed in more recent versions.

**Comment by Dasky14** [comment]
Gotcha. 👍
This was on the version updated from mod browser yesterday. (v1.2.1)
