### ISSUE TITLE
Exception list bug

### ISSUE THREAD

**Issue by Veeneeceeus** [JPANv2/ResearchFrom14#2]
I can't set an item as negative value, to prevent it from being researchable.

**Comment by Veeneeceeus** [comment]
I can change it to -1 through the Tmodloader config folder, however it doesn't work in the in-game menu.

**Comment by JPANv2** [comment]
The TMod Menu does not allow negative numbers by default. So I just changed the config to accept 0 as the default "unresearchable" value. Do note that this is the default value as well, so new entries will start as unresearchable until a new value is provided.
